language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
before_install:
  - sudo apt-get install -y python-smbus
  - sudo apt-get install -y i2c-tools
install:
  - pip install unittest2
  - pip install adafruit_pca9685
  - pip install flask
  - pip install flask_bootstrap
  - pip install flask_sqlalchemy
  - pip install flask_wtf
  - pip install pathlib
script: python smars_library/test_suite.py
